name: modul_3_latihan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^1.1.0
  dio: ^5.3.2
  webview_flutter: ^4.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
