// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASYegZiSZu37AoH8TUQ4p78uu2Z4EhIjg',
    appId: '1:286833354873:web:82dc90b8e3e8619dbb0ca8',
    messagingSenderId: '286833354873',
    projectId: 'pem-mobile23',
    authDomain: 'pem-mobile23.firebaseapp.com',
    storageBucket: 'pem-mobile23.appspot.com',
    measurementId: 'G-HN1592XNWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9m0l9k9VAm27fElA9QwXVHkVvaoXuIsI',
    appId: '1:286833354873:android:e67725dda3f90d07bb0ca8',
    messagingSenderId: '286833354873',
    projectId: 'pem-mobile23',
    storageBucket: 'pem-mobile23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MjWwgqTJV2HZSvyHMSAtxBQuQ210-s4',
    appId: '1:286833354873:ios:ff1828820b588ee9bb0ca8',
    messagingSenderId: '286833354873',
    projectId: 'pem-mobile23',
    storageBucket: 'pem-mobile23.appspot.com',
    iosBundleId: 'com.naufal.modul2Prak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9MjWwgqTJV2HZSvyHMSAtxBQuQ210-s4',
    appId: '1:286833354873:ios:c359652ab40fd30dbb0ca8',
    messagingSenderId: '286833354873',
    projectId: 'pem-mobile23',
    storageBucket: 'pem-mobile23.appspot.com',
    iosBundleId: 'com.naufal.modul2Prak.RunnerTests',
  );
}
